---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployments.yaml
- load-generator.yaml
configMapGenerator:
- name: example-workload
  namespace: default
  files:
  - service.clj
